<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QT-INBG-LT1475" ignored="6" name="Test Basics 1" tests="12" failures="5" timestamp="2023-07-21T18:08:28 IST" time="8.249" errors="0">
  <testcase name="deleteUser" time="5.526" classname="com.qa.tests.DeleteTests">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;204&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <204> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$11.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at com.qa.tests.DeleteTests.deleteUser(DeleteTests.java:29)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
  <testcase name="getIndividualCommentsForUser" time="5.598" classname="com.qa.tests.GetTests">
    <failure type="java.lang.AssertionError" message="
Expecting actual not to be empty">
      <![CDATA[java.lang.AssertionError: 
Expecting actual not to be empty
at com.qa.tests.GetTests.getIndividualCommentsForUser(GetTests.java:150)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getIndividualCommentsForUser -->
  <testcase name="getComments" time="5.824" classname="com.qa.tests.GetTests"/>
  <testcase name="getPostsWithBasePath" time="5.827" classname="com.qa.tests.GetTests"/>
  <testcase name="getUser" time="5.831" classname="com.qa.tests.GetTests">
    <failure type="java.lang.AssertionError" message="
Expecting
  com.qa.pojo.User@72f62e7b
to have a property or a field named &amp;quot;id&amp;quot; with value
  &amp;quot;3708305&amp;quot;
but value was:
  &amp;quot;3778659&amp;quot;
(static and synthetic fields are ignored)">
      <![CDATA[java.lang.AssertionError: 
Expecting
  com.qa.pojo.User@72f62e7b
to have a property or a field named "id" with value
  "3708305"
but value was:
  "3778659"
(static and synthetic fields are ignored)
at com.qa.tests.GetTests.getUser(GetTests.java:75)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getUser -->
  <testcase name="getPostsWithQueryParameter" time="5.844" classname="com.qa.tests.GetTests"/>
  <testcase name="getUsers" time="1.854" classname="com.qa.tests.GetTests"/>
  <testcase name="postCreateUserWithString" time="1.665" classname="com.qa.tests.PostTests">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;201&amp;gt; but was &amp;lt;422&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <422>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$11.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at com.qa.tests.PostTests.postCreateUserWithString(PostTests.java:40)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- postCreateUserWithString -->
  <testcase name="postCreateUserJsonObject" time="2.431" classname="com.qa.tests.PostTests"/>
  <testcase name="putUpdateUserPojo" time="2.259" classname="com.qa.tests.PutTests">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$11.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:101)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at com.qa.tests.PutTests.putUpdateUserPojo(PutTests.java:40)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- putUpdateUserPojo -->
  <testcase name="postCreateUserWithMap" time="2.289" classname="com.qa.tests.PostTests"/>
  <testcase name="postCreateUserPojo" time="2.4" classname="com.qa.tests.PostTests"/>
  <testcase name="@AfterSuite tearDownSuite" time="0.0" classname="com.qa.setup.Base">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase name="@AfterSuite tearDownSuite" time="0.0" classname="com.qa.setup.Base">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase name="@AfterSuite tearDownSuite" time="0.0" classname="com.qa.setup.Base">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase name="@BeforeSuite setUpSuite" time="0.0" classname="com.qa.setup.Base">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpSuite -->
  <testcase name="@BeforeSuite setUpSuite" time="0.0" classname="com.qa.setup.Base">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpSuite -->
  <testcase name="@BeforeSuite setUpSuite" time="0.0" classname="com.qa.setup.Base">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpSuite -->
</testsuite> <!-- Test Basics 1 -->
