<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="QT-INBG-LT1475" name="com.qa.tests.GetTests" tests="6" failures="2" timestamp="2023-07-21T18:08:28 IST" time="30.785" errors="0">
  <testcase name="getComments" time="5.825" classname="com.qa.tests.GetTests"/>
  <testcase name="getIndividualCommentsForUser" time="5.599" classname="com.qa.tests.GetTests">
    <failure type="java.lang.AssertionError" message="
Expecting actual not to be empty">
      <![CDATA[java.lang.AssertionError: 
Expecting actual not to be empty
at com.qa.tests.GetTests.getIndividualCommentsForUser(GetTests.java:150)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getIndividualCommentsForUser -->
  <testcase name="getPostsWithQueryParameter" time="5.846" classname="com.qa.tests.GetTests"/>
  <testcase name="getUsers" time="1.855" classname="com.qa.tests.GetTests"/>
  <testcase name="getPostsWithBasePath" time="5.828" classname="com.qa.tests.GetTests"/>
  <testcase name="getUser" time="5.832" classname="com.qa.tests.GetTests">
    <failure type="java.lang.AssertionError" message="
Expecting
  com.qa.pojo.User@72f62e7b
to have a property or a field named &quot;id&quot; with value
  &quot;3708305&quot;
but value was:
  &quot;3778659&quot;
(static and synthetic fields are ignored)">
      <![CDATA[java.lang.AssertionError: 
Expecting
  com.qa.pojo.User@72f62e7b
to have a property or a field named "id" with value
  "3708305"
but value was:
  "3778659"
(static and synthetic fields are ignored)
at com.qa.tests.GetTests.getUser(GetTests.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getUser -->
</testsuite> <!-- com.qa.tests.GetTests -->
